import { isReservedEnvName } from '../src/reserved-env';

describe('isReservedEnvName', () => {
  test.each([
    // 1. Direct code execution hooks
    'BASH_ENV',
    'ENV',
    'SHELLOPTS',
    'BASH_FUNC_foo',
    'PS4',
    'PROMPT_COMMAND',
    'NODE_OPTIONS',
    'JAVA_TOOL_OPTIONS',
    '_JAVA_OPTIONS',
    'MAVEN_OPTS',
    'GRADLE_OPTS',
    'RUBYOPT',
    'PERL5OPT',
    'PYTHONSTARTUP',
    'PYTHONBREAKPOINT',
    'GOFLAGS',
    'RUSTC_WRAPPER',
    'CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER',
    'CORECLR_PROFILER',
    'COR_PROFILER_PATH',
    'DOTNET_STARTUP_HOOKS',
    'LESSOPEN',
    'PAGER',
    'SSH_ASKPASS',
    'GIT_ASKPASS',
    'MAKEFLAGS',
    'CC',
    'LD',
    'CGO_LDFLAGS',
    // 2. Loader injection
    'LD_PRELOAD',
    'LD_AUDIT',
    'LD_LIBRARY_PATH',
    'GLIBC_TUNABLES',
    'GCONV_PATH',
    'HOSTALIASES',
    'TERMINFO_DIRS',
    'MALLOC_TRACE',
    'DYLD_INSERT_LIBRARIES',
    'DYLD_PRINT_LIBRARIES',
    // 3. Search paths and identity
    'PATH',
    'IFS',
    'HOME',
    'USERPROFILE',
    'APPDATA',
    'XDG_CONFIG_HOME',
    'XDG_DATA_DIRS',
    'PSMODULEPATH',
    'PYTHONPATH',
    'NODE_PATH',
    'CLASSPATH',
    'GOPATH',
    'GOTOOLCHAIN',
    'CARGO_HOME',
    'RUSTUP_TOOLCHAIN',
    'PHP_INI_SCAN_DIR',
    'GRADLE_USER_HOME',
    // 4. Package manager redirection
    'NPM_CONFIG_REGISTRY',
    'NPM_CONFIG_SCRIPT_SHELL',
    'PIP_INDEX_URL',
    'UV_INDEX_URL',
    'POETRY_REPOSITORIES_FOO_URL',
    'BUNDLE_GEMFILE',
    'CARGO_REGISTRIES_CRATES_IO_INDEX',
    'GOPROXY',
    'GOINSECURE',
    'YARN_RC_FILENAME',
    'TF_CLI_CONFIG_FILE',
    // 5. Git
    'GIT_SSH_COMMAND',
    'GIT_EXTERNAL_DIFF',
    'GIT_TEMPLATE_DIR',
    'GIT_CONFIG_GLOBAL',
    'GIT_SSL_NO_VERIFY',
    'SSH_AUTH_SOCK',
    // 6. Transport security
    'HTTPS_PROXY',
    'NO_PROXY',
    'SSL_CERT_FILE',
    'CURL_CA_BUNDLE',
    'NODE_EXTRA_CA_CERTS',
    'NODE_TLS_REJECT_UNAUTHORIZED',
    'NETRC',
    'WGETRC',
    'OPENSSL_CONF',
    // 7. Cloud and container
    'AWS_CONFIG_FILE',
    'AWS_SHARED_CREDENTIALS_FILE',
    'AWS_CONTAINER_CREDENTIALS_FULL_URI',
    'AWS_EC2_METADATA_SERVICE_ENDPOINT',
    'AWS_ENDPOINT_URL_S3',
    'AWS_WEB_IDENTITY_TOKEN_FILE',
    'MSI_ENDPOINT',
    'IDENTITY_HEADER',
    'GOOGLE_APPLICATION_CREDENTIALS',
    'GCE_METADATA_HOST',
    'CLOUDSDK_CONFIG',
    'DOCKER_HOST',
    'DOCKER_CONFIG',
    'KUBECONFIG',
    'KUBERNETES_SERVICE_HOST',
    // Windows runners
    'COMSPEC',
    'PATHEXT',
    'PSMODULEPATH',
    'PSEXECUTIONPOLICYPREFERENCE',
    'WINDIR',
    'SYSTEMROOT',
    'PROGRAMFILES',
    'PROGRAMW6432',
    'MSBUILDUSEREXTENSIONSPATH',
    'MSBUILD_EXE_PATH',
    'VCTARGETSPATH',
    'VSINSTALLDIR',
    '__COMPAT_LAYER',
    'CHOCOLATEYINSTALL',
    'SCOOP',
    'MSYSTEM',
    'MSYS2_ARG_CONV_EXCL',
    'CYGWIN',
    'WSLENV',
    // 8. Runner internals
    'GITHUB_ENV',
    'GITHUB_PATH',
    'GITHUB_EVENT_PATH',
    'RUNNER_TEMP',
    'ACTIONS_RUNNER_HOOK_JOB_STARTED',
    'ACTIONS_ID_TOKEN_REQUEST_TOKEN',
    'ACTIONS_ALLOW_UNSECURE_COMMANDS',
    'INPUT_SITE_ID',
    'STATE_FOO',
  ])('treats %s as reserved', (name) => {
    expect(isReservedEnvName(name)).toBe(true);
  });

  test('is case-insensitive', () => {
    expect(isReservedEnvName('git_ssh_command')).toBe(true);
    expect(isReservedEnvName('Ld_Preload')).toBe(true);
  });

  test.each([
    // Credential-shaped names the action exists to deliver, including ones that sit next to
    // a reserved namespace. Rejecting these would break the action's primary use case.
    'DATABASE_URL',
    'API_KEY',
    'PASSWORD',
    'CONNECTIONSTRING',
    'NPM_TOKEN',
    'AWS_ACCESS_KEY_ID',
    'AWS_SECRET_ACCESS_KEY',
    'AWS_SESSION_TOKEN',
    'AWS_REGION',
    'ARM_CLIENT_SECRET',
    'ARM_CLIENT_ID',
    'TF_VAR_DB_PASSWORD',
    'ORG_GRADLE_PROJECT_SIGNING_KEY',
    'CARGO_REGISTRY_TOKEN',
    'DOCKER_USERNAME',
    'DOCKER_PASSWORD',
    'SONAR_TOKEN',
    'GOOGLE_PROJECT_ID',
    // A namespaced name: the field key was dangerous, the resolved variable is not.
    'APP_LD_PRELOAD',
    'MY_APP_GIT_SSH_COMMAND',
  ])('leaves %s alone', (name) => {
    expect(isReservedEnvName(name)).toBe(false);
  });
});
