version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-gh-actions:
        update-types:
          - minor
          - patch
      major-gh-actions:
        update-types:
          - major
  - package-ecosystem: npm
    directories:
      - '**/*'
    schedule:
      interval: weekly
    groups:
      minor-npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      minor-npm-production:
        dependency-type: production
        update-types:
          - minor
          - patch
      major-npm-development:
        dependency-type: development
        update-types:
          - major
      major-npm-production:
        dependency-type: production
        update-types:
          - major
