DISABLE_LINTERS:
  - TYPESCRIPT_STANDARD # Prefer prettier
  - TYPESCRIPT_PRETTIER # Configured in integration workflow
  - MARKDOWN_MARKDOWN_LINK_CHECK # Redundant. Prefer lychee.
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER # Forces excessive column padding on tables with long descriptions; GitHub renders fine without it.
  - SPELL_CSPELL # Not helpful. Configuration is way too tedious just to catch the odd typo.
  - SPELL_LYCHEE
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_GITLEAKS
  - REPOSITORY_GRYPE
  - REPOSITORY_LS_LINT
  - REPOSITORY_SECRETLINT
  - REPOSITORY_SYFT
  - REPOSITORY_TRIVY_SBOM
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_OSV_SCANNER

FILTER_REGEX_EXCLUDE: (dist/)
TYPESCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (CHANGELOG\.md)
REPOSITORY_TRIVY_COMMAND_REMOVE_ARGUMENTS: '--scanners vuln,misconfig'
REPOSITORY_TRIVY_ARGUMENTS: '--scanners misconfig'
SARIF_REPORTER: true
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
