name: '{{ template.name }}'
description: '{{ template.description }}'
author: BeyondTrust/{{ template.owner }}
inputs: # Your inputs go here.
  message:
    description: |
      A super secret message.
outputs:
  message:
    description: |
      A super secret output.
runs:
  using: 'node20'
  main: 'dist/index.js'
