name: 'workload-credentials'
description: 'A typescript action to get secrets from BeyondTrust workload credentials'
author: BeyondTrust/volt
inputs:
  site-id:
    description: 'The BeyondTrust site ID (UUID).'
    required: true
  secret-type:
    description: 'The type of secret to retrieve. Must be "static" or "dynamic".'
    required: true
  secret-path:
    description: 'The path to the secret in BeyondTrust Secrets Safe.'
    required: true
outputs:
  secret:
    description: 'The retrieved secret value.'
runs:
  using: 'node20'
  main: 'dist/index.js'
