name: 'Build'

on:
  pull_request:
    branches:
      - master

permissions:
  contents: none

env:
  TARGET_REPOSITORY: eng-generic-qa-local
  TARGET_PATH: beyondtrust/devx/actions
  TARGET_NAME: 'workload-credentials'

jobs:
  build-test:
    if: ${{ github.actor == 'beyondtrust-release-app[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Determine version
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: version
        with:
          script: |
            const version = require("./package.json").version
            core.setOutput("version", version);

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20

      - name: Setup JFrog
        uses: beyondtrust/setup-jfrog-cli@26d84636538c322aed2f822374a0b976b23caa81 # v2.4.3
        id: configure

      - name: Configure JFrog
        run: |
          echo "JFROG_CLI_BUILD_NUMBER=${{ steps.version.outputs.version }}-${{ github.run_number }}" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: jf npm ci --ignore-scripts

      - name: Build and Package
        run: npm run all

      - name: Scan Vulnerabilities
        uses: beyondtrust/dependency-vulnerability-scan@f263be345e51426f77ca2a8fc73c8b481d3e5062 # v3.0.9

      - name: Audit
        uses: beyondtrust/security-validation-action@6a9cc1a4f0e5cc4650e3423430cfb56942f6bd7e # v2.2.0

      - name: Publish
        run: |
          jf rt u "*" "${{ env.TARGET_REPOSITORY }}/${{ env.TARGET_PATH }}/${{env.TARGET_NAME }}_${{ env.JFROG_CLI_BUILD_NUMBER }}.zip" --archive zip
          jf rt build-add-git
          jf rt build-collect-env
          jf rt build-publish ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }}
        working-directory: dist
