name: 'Integration'

on:
  pull_request:

permissions:
  contents: none

jobs:
  integration:
    name: 'Integration'
    permissions:
      contents: read
    uses: BeyondTrust/workflows/.github/workflows/integration-node.yaml@51e9f52f8446a28edae9c7277ce1a612b86570ea # v4.13.1
    secrets: inherit
    with:
      node-version: '20'
