name: Promote Release Candidate

on:
  release:
    types: [published]

permissions:
  contents: none

env:
  TARGET_REPOSITORY: eng-generic-prod-local

jobs:
  promote:
    name: Promote
    uses: BeyondTrust/workflows/.github/workflows/promote-jfrog-build.yaml@94e83e3a94caaededfa1d5ee73077c334d0b1399 # v4.13.2
    secrets: inherit
