name: Promote Release Candidate

on:
  release:
    types: [published]

permissions:
  contents: none

env:
  TARGET_REPOSITORY: eng-generic-prod-local

jobs:
  promote:
    name: Promote
    uses: BeyondTrust/workflows/.github/workflows/promote-jfrog-build.yaml@51e9f52f8446a28edae9c7277ce1a612b86570ea # v4.13.1
    secrets: inherit
