name: Publish SBOM

on:
  release:
    types: [published]

permissions:
  contents: none

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish SBOM as release assest
        uses: BeyondTrust/publish-xray-sbom@b788a3e12084398c2f0af5e682c32bebe3a29296 # v2.1.0
        with:
          jfrog-access-token: ${{ secrets.JFROG_RT_READ_XRAY }}
